[package]
name = "belly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/belly_core",
    "crates/belly_macro",
    "crates/belly_widgets",
    "crates/tagstr",
]

[dependencies]
bevy = { path = "../bevy" }
tagstr = { path = "crates/tagstr" }
belly_macro = { path = "crates/belly_macro" }
belly_core = { path = "crates/belly_core" }
belly_widgets = { path = "crates/belly_widgets" }

[[example]]
name = "text_input"
path = "examples/text-input.rs"
