[package]
name = "belly_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9", path = "../../../bevy" } # DOWNGRADE 0.9 -> 0.8 2023-01-05
quote = "1.0.21"
syn-rsx = { git = "https://github.com/stoically/syn-rsx.git" }
# syn-rsx = { git = "https://github.com/jkb0o/syn-rsx.git", branch = "add_syn_printing_feature" }
belly_core = { path = "../belly_core" }
proc-macro2 = "1.0.47"
procout = "0.1.13"
syn = "1.0.103"
toml = "0.5.10"
# syn = { version = "1.0.105", features = ["full", "parsing", "printing", "extra-traits"] }
